# Generated by Django 3.2.4 on 2021-06-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicky', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='note',
            new_name='note_name',
        ),
    ]
